### PR TITLE
Added channel 4 to HM-RC-Key4-2 and removed "write"

### PR DESCRIPTION
**Pull request by hfedcba**
I also removed the part for HM-RC-Sec4-2 as the remote is identical to the HM-RC-Key4-2 (from a client point of view).

### CODE REVIEW

**Comment by HealsCodes** [comment]
Looking good, is there any reason to remove the `write` section?
I can imagine it doesn't make a lot of sense writing to actions on a remote since there is nothing to trigger (compared to i.e. the BOOST of a thermo) but trusting the XML specs they _should_ be writeable.

**Comment by hfedcba** [comment]
Yes, the XML file should be trusted. So don't change anything in the conversion. I'm converting the device description file from eQ-3 and they have the keys writeable for whatever reason. I need to change my converter to make them read only.

**Comment by HealsCodes** [comment]
That's what I'm using too (at least in this first set of releases) - I'm parsing the files from the eQ-3 SDK.
I would rather use the files shipped with Homegear (even if only for the instant support for MAX!, INSTEON and Hue) but their structure as more complex and - THB - I couldn't finde a good documentation for it.

**Comment by hfedcba** [comment]
Yes, the documentation is still missing... But you can find the schema here: https://github.com/Homegear/Homegear_Device_XML_Schema

**Comment by HealsCodes** [comment]
Nice! 

I wrote a new script to process the descriptions used in the Homegear plugins. 

If you like you can take a look at the homematic.json inside the feature/convert-hg-xml branch. 

It looks promising :)

**Pull request merged**
